package com.oreon.proj.onepack;

import javax.persistence.Embeddable;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

@Embeddable
public class Address extends AddressBase implements java.io.Serializable {
	private static final long serialVersionUID = -1384484729L;
}
