package com.oreon.proj;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

public class Untitled1 extends Untitled1Base implements java.io.Serializable {
	private static final long serialVersionUID = -695983207L;
}
