package com.oreon.proj;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

public class investor extends investorBase implements java.io.Serializable {
	private static final long serialVersionUID = -2101802675L;
}
