package com.oreon.proj.univeris.data;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

import org.hibernate.validator.constraints.NotBlank;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

//should not gen advice

public class InvestorProfile extends InvestorProfileBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = 1062433502L;
	
	
	@NotBlank
	private String code;


	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}


	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}
}
