package com.oreon.proj.onepack;

import javax.persistence.MappedSuperclass;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

@MappedSuperclass
public class Person extends PersonBase implements java.io.Serializable {
	private static final long serialVersionUID = -1812360410L;
}
